"""Prepare everything the investigation needs. Idempotent; safe to run on every deploy.

    python -m backend.precompute            # whatever is missing
    python -m backend.precompute --synthetic --force   # regenerate the simulated dataset
    python -m backend.precompute --yolo CAM_A1          # (re)track one real camera

Per camera in data/config/cameras.json:
  - simulated camera (has "sim")       → generated by backend.synth.make_all
  - real camera with data/footage/<id>.mp4 → YOLO + ByteTrack (needs requirements-yolo.txt), then calibrate
  - raw tracks present but no ground tracks → calibrate only
"""
import argparse
import importlib.util
import logging
import os
import sys

from backend.config import CONFIG_DIR, FOOTAGE_DIR, GT_DIR, TRACKS_DIR

log = logging.getLogger("almost.precompute")


def _have_yolo():
    return importlib.util.find_spec("ultralytics") is not None


def status():
    from backend.perception.camera import load_cameras
    rows = []
    for c in load_cameras():
        cid = c["camera_id"]
        rows.append({"camera_id": cid, "simulated": "sim" in c,
                     "footage": (FOOTAGE_DIR / f"{cid}.mp4").exists(),
                     "raw_tracks": (TRACKS_DIR / f"{cid}.raw.parquet").exists(),
                     "tracks": (TRACKS_DIR / f"{cid}.parquet").exists()})
    return rows


def main(argv=None):
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    ap = argparse.ArgumentParser()
    ap.add_argument("--synthetic", action="store_true", help="(re)generate the simulated dataset")
    ap.add_argument("--force", action="store_true", help="re-calibrate real cameras even if tracks exist")
    ap.add_argument("--yolo", nargs="*", metavar="CAM", help="run YOLO on these cameras (all real ones if empty)")
    args = ap.parse_args(argv)

    st = status() if (CONFIG_DIR / "cameras.json").exists() else []
    need_synth = args.synthetic or not st or (
        any(r["simulated"] for r in st)
        and (any(r["simulated"] and not (r["tracks"] and r["footage"]) for r in st)
             or not (GT_DIR / "events.json").exists()))
    if need_synth:
        log.info("generating simulated dataset (footage, tracks, ground truth)")
        from backend.synth import make_all
        make_all.main([])

    from backend.perception.calibrate import calibrate_camera
    from backend.perception.track import run_yolo
    for r in status():
        cid = r["camera_id"]
        if r["simulated"]:
            continue
        want_yolo = args.yolo is not None and (not args.yolo or cid in args.yolo)
        if r["footage"] and (want_yolo or not r["raw_tracks"]):
            if not _have_yolo():
                log.error("%s: footage present but ultralytics is not installed "
                          "(pip install -r requirements-yolo.txt)", cid)
                continue
            log.info("%s: YOLO + ByteTrack", cid)
            run_yolo(cid, device=os.environ.get("YOLO_DEVICE") or None)
            calibrate_camera(cid)
        elif r["raw_tracks"] and (not r["tracks"] or args.force):
            log.info("%s: calibrating", cid)
            calibrate_camera(cid)
        elif not r["footage"] and not r["tracks"]:
            log.warning("%s: no footage at data/footage/%s.mp4 and no tracks", cid, cid)

    for r in status():
        log.info("%-8s simulated=%-5s footage=%-5s tracks=%s", r["camera_id"], r["simulated"], r["footage"], r["tracks"])
    missing = [r["camera_id"] for r in status() if not r["tracks"]]
    if missing:
        log.warning("cameras without tracks (excluded from investigations): %s", missing)
    return 0


if __name__ == "__main__":
    sys.exit(main())
